### ISSUE TITLE
SQL Connection Expires

### ISSUE THREAD

**Issue by PseudoResonance** [Matt-MX/ReconnectVelocity#13]
I believe you just need to add the `autoReconnect=true` connection property to the end of your connection string to allow JDBC to stay connected long term.

<details>
<summary>Stacktace</summary>
  
```
[18:17:59 ERROR]: com.mysql.cj.jdbc.exceptions.CommunicationsException: The last packet successfully received from the server was 37,855,723 milliseconds ago. The last packet sent successfully to the server was 37,855,724 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
[18:17:59 ERROR]:       at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)
[18:17:59 ERROR]:       at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
[18:17:59 ERROR]:       at com.mysql.cj.jdbc.StatementImpl.executeQuery(StatementImpl.java:1201)
[18:17:59 ERROR]:       at com.mattmx.reconnect.util.storage.MySqlStorage.getLastServer(MySqlStorage.java:50)
[18:17:59 ERROR]:       at com.mattmx.reconnect.listener.Listener.choose(Listener.java:28)
[18:17:59 ERROR]:       at com.mattmx.reconnect.listener.Lmbda$44.execute(Unknown Source)
[18:17:59 ERROR]:       at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56)
[18:17:59 ERROR]:       at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:597)
[18:17:59 ERROR]:       at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:478)
[18:17:59 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[18:17:59 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[18:17:59 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:840)
[18:17:59 ERROR]: Caused by: com.mysql.cj.exceptions.CJCommunicationsException: The last packet successfully received from the server was 37,855,723 milliseconds ago. The last packet sent successfully to the server was 37,855,724 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
[18:17:59 ERROR]:       at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[18:17:59 ERROR]:       at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[18:17:59 ERROR]:       at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[18:17:59 ERROR]:       at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[18:17:59 ERROR]:       at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[18:17:59 ERROR]:       at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
[18:17:59 ERROR]:       at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
[18:17:59 ERROR]:       at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
[18:17:59 ERROR]:       at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
[18:17:59 ERROR]:       at com.mysql.cj.protocol.a.NativeProtocol.send(NativeProtocol.java:628)
[18:17:59 ERROR]:       at com.mysql.cj.protocol.a.NativeProtocol.sendCommand(NativeProtocol.java:683)
[18:17:59 ERROR]:       at com.mysql.cj.protocol.a.NativeProtocol.sendQueryPacket(NativeProtocol.java:1051)
[18:17:59 ERROR]:       at com.mysql.cj.protocol.a.NativeProtocol.sendQueryString(NativeProtocol.java:997)
[18:17:59 ERROR]:       at com.mysql.cj.NativeSession.execSQL(NativeSession.java:663)
[18:17:59 ERROR]:       at com.mysql.cj.jdbc.StatementImpl.executeQuery(StatementImpl.java:1169)
[18:17:59 ERROR]:       ... 9 more
[18:17:59 ERROR]: Caused by: java.net.SocketException: Connection reset by peer
[18:17:59 ERROR]:       at java.base/sun.nio.ch.NioSocketImpl.implWrite(NioSocketImpl.java:425)
[18:17:59 ERROR]:       at java.base/sun.nio.ch.NioSocketImpl.write(NioSocketImpl.java:445)
[18:17:59 ERROR]:       at java.base/sun.nio.ch.NioSocketImpl$2.write(NioSocketImpl.java:831)
[18:17:59 ERROR]:       at java.base/java.net.Socket$SocketOutputStream.write(Socket.java:1035)
[18:17:59 ERROR]:       at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
[18:17:59 ERROR]:       at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142)
[18:17:59 ERROR]:       at com.mysql.cj.protocol.a.SimplePacketSender.send(SimplePacketSender.java:55)
[18:17:59 ERROR]:       at com.mysql.cj.protocol.a.TimeTrackingPacketSender.send(TimeTrackingPacketSender.java:50)
[18:17:59 ERROR]:       at com.mysql.cj.protocol.a.NativeProtocol.send(NativeProtocol.java:619)
[18:17:59 ERROR]:       ... 14 more
[18:17:59 INFO]: [server connection] PLAYER CONNECTED
[18:18:00 ERROR]: java.sql.SQLException: No operations allowed after statement closed.
[18:18:00 ERROR]:       at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
[18:18:00 ERROR]:       at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
[18:18:00 ERROR]:       at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
[18:18:00 ERROR]:       at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
[18:18:00 ERROR]:       at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
[18:18:00 ERROR]:       at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:82)
[18:18:00 ERROR]:       at com.mysql.cj.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1335)
[18:18:00 ERROR]:       at com.mysql.cj.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2085)
[18:18:00 ERROR]:       at com.mysql.cj.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1246)
[18:18:00 ERROR]:       at com.mattmx.reconnect.util.storage.MySqlStorage.setLastServer(MySqlStorage.java:38)
[18:18:00 ERROR]:       at com.mattmx.reconnect.listener.Listener.change(Listener.java:66)
[18:18:00 ERROR]:       at com.mattmx.reconnect.listener.Lmbda$42.execute(Unknown Source)
[18:18:00 ERROR]:       at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56)
[18:18:00 ERROR]:       at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:597)
[18:18:00 ERROR]:       at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:478)
[18:18:00 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[18:18:00 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[18:18:00 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:840)
[18:18:00 ERROR]: Caused by: com.mysql.cj.exceptions.StatementIsClosedException: No operations allowed after statement closed.
[18:18:00 ERROR]:       at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[18:18:00 ERROR]:       at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[18:18:00 ERROR]:       at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[18:18:00 ERROR]:       at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[18:18:00 ERROR]:       at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[18:18:00 ERROR]:       at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
[18:18:00 ERROR]:       at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:85)
[18:18:00 ERROR]:       at com.mysql.cj.jdbc.StatementImpl.checkClosed(StatementImpl.java:336)
[18:18:00 ERROR]:       at com.mysql.cj.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1250)
[18:18:00 ERROR]:       ... 11 more
```
</details>

**Comment by Matt-MX** [comment]
Fixed in #14
